### ISSUE TITLE
Keyboard not showing when TextField is tapped

### ISSUE THREAD

**Issue by nickolaylo** [EddieKamau/flutter_overlay_apps#3]

**Comment by X-SLAYER** [comment]
checkout this package [flutter_overlay_window](https://pub.dev/packages/flutter_overlay_window) it's optimized version of this package the text field works fine when you add the specific flag like it mentioned here [1#issue](https://github.com/X-SLAYER/flutter_overlay_window/issues/1#issuecomment-1113681412)
